#!/usr/bin/env bash
set -x
export EXTRA_CONTAINER_OPTS="\
    --detach \
    --init
"

$(dirname $0)/run-container $@

source $(dirname $0)/common.sh
docker exec \
  -d \
  $CONTAINER_NAME \
  /bin/sh -c \
  "/home/user/tomcat/apache-tomcat-10.0.8/bin/start.sh"
