#!/usr/bin/env bash
set -x
source utils.sh

tar -xvf eclipse-jee-2020-03-R-incubation-linux-gtk-x86_64.tar.gz --directory /home/${CONTAINER_USER:?}/
chown ${CONTAINER_USER:?}:${CONTAINER_USER:?} /home/${CONTAINER_USER:?}/eclipse/*
