#!/usr/bin/env bash
set -x
source utils.sh

cd /home/${CONTAINER_USER:?}
mkdir tomcat
cd tomcat
wget https://downloads.apache.org/tomcat/tomcat-10/v10.0.8/bin/apache-tomcat-10.0.8.tar.gz
tar -xvf apache-tomcat-10.0.8.tar.gz --directory ./
chown -R ${CONTAINER_USER:?}:${CONTAINER_USER:?} /home/${CONTAINER_USER:?}/tomcat/*
rm apache-tomcat-10.0.8.tar.gz